Fix/back-carlitossaul-add-message-of-error
LabsPlus/API-Email-Services pull request #27
Opened 2024-04-24 19:06 UTC by Carlitossaul

Amigo addicionei a mensagem de error que tava precisando para exibir no front.

2024-04-25 11:10 UTC, WesleyUlisses approved these changes

2024-04-25 11:11 UTC, WesleyUlisses requested changes
Bom dia amigo, essa mensagem na controller não é necessaria, a mensagem é retornada da service, via erro, quando o email não é encotrado, esta parte é funcional já

2024-04-25 13:13 UTC, Carlitossaul commented
Amigo ja fez as correcoes necesarias. Pode fazer o review?

2024-04-25 23:36 UTC, WesleyUlisses requested changes

2024-04-25 23:36 UTC, WesleyUlisses commented on src/repositories/dao/userDao.ts
> +            return user ? user : 'O sistema não encontra o email no banco de dados.';
Amigo, podeira alterar esta mensagem para "Email não encontrado na base de dados"

2024-04-26 00:09 UTC, WesleyUlisses approved these changes

2024-04-26 00:09 UTC, merged